isi_pop_site_homepage:
    path:     /
    defaults: { _controller: IsiPopSiteBundle:Yts:index }
    
isi_pop_site_stream_yts:
    path: /stream/yts/{id}-{url}
    defaults: { _controller: IsiPopSiteBundle:Stream:yts }
    requirements:
        _method:  GET
        id:  \d+
        url: '[a-zA-Z0-9-:_\/-\s.]+'
