isi_pop_site_homepage:
    path:     /
    defaults: { _controller: IsiPopSiteBundle:Default:index }
    
isi_pop_site_stream:
    path: /stream/{id}-{file}
    defaults: { _controller: IsiPopSiteBundle:Stream:index }
    requirements:
        _method:  GET
        id:  \d+
