isi_pop_site_homepage:
    path:     /{page}/{search}
    defaults: { _controller: IsiPopSiteBundle:Yts:index , page: 1 , search: ''}
    requirements:
        _method: GET
        page: \d+

isi_pop_site_homepage_Form_search:
    path:   /form/
    defaults: { _controller: IsiPopSiteBundle:Yts:searchForm }
    requirements:
        _method: POST

isi_pop_site_stream_yts:
    path: /stream/yts/{id}/{url}
    defaults: { _controller: IsiPopSiteBundle:Stream:yts }
    requirements:
        _method:  GET
        id:  \d+
        

      
        
